### ISSUE TITLE
HMR support

### ISSUE THREAD

**Issue by nchanged** [TobiasTimm/fuse-box-ng-template-plugin#1]
Hi!
Great plugin, I think i've managed to make HMR work
here, how:

index.ts
```
if( process.env.NODE_ENV === "development"){
  require("./hmr");
}
```

hmr.js

```
const customizedHMRPlugin = {
    hmrUpdate: ({ type, path, content }) => {
        if (type === "js") {
            // remove root
            var elem = document.getElementById('root');
            elem.parentNode.removeChild(elem);
            // re-create everything
            const div = document.createElement('div');
            div.setAttribute('id', 'root');
            div.innerHTML = `<app></app>`;

            document.body.appendChild(div);
            FuseBox.flush();
            FuseBox.dynamic(path, content);
            if (FuseBox.mainFile) {
                FuseBox.import(FuseBox.mainFile)
            }
            return true;
        }
    }
}

let alreadyRegistered = false;
if (!window.hmrRegistered) {
    window.hmrRegistered = true;
    FuseBox.addPlugin(customizedHMRPlugin);
}
```

Do you think we can automatically inject this code?

**Comment by tobiastimm** [comment]
Sounds good. Does fuse-box has something like this? https://github.com/jharris4/html-webpack-include-assets-plugin

**Comment by tobiastimm** [comment]
Or maybe create a virtual file on loading the ngtemplate plugin when hmr is on

**Comment by tobiastimm** [comment]
@nchanged I've tried your hmr solution, amazing work :smile: . Only downside is that the application state is lost. There was a hot-loader for webpack once, but I think it isn't supported anymore
https://github.com/vitaliy-bobrov/angular-hot-loader

**Comment by nchanged** [comment]
It’s lost, but we can preserve it by collecting scopes in controllers, storing them and then recreating, but that looks like a framework to me (which I don’t mind having)

Nonetheless it’s better than reloading the entire page

**Comment by tobiastimm** [comment]
yeah. It's great to have hmr in any way :+1:. 
What would be your preferred way to integrate this functionality? Is there some way to create a virtual file in `public init(context: WorkflowContext)`? Or maybe another plugin? 

Technically I would say it isn't a functionality that has something to do with the purpose of this plugin.

**Comment by nchanged** [comment]
maybe we just update the example :) or create an npm module to help setting it up

**Comment by tobiastimm** [comment]
Would be great if we set something up like a `fuse-box-cli` to kickstart your awesome `fuse-box` apps :smiley:

**Comment by tobiastimm** [comment]
@nchanged what about the idea of a fuse-box-cli with project seeds? I think it would help people. Something like the angular-cli, vue-cli, create-react-app.

**Comment by nchanged** [comment]
@TobiasTimm that would be cool. I think that CLI should be able to boostrap any kind of seed.  I've been thinking of CLI zero config. ;-)

**Comment by tobiastimm** [comment]
Sounds great. I will help where I can

**Comment by tobiastimm** [comment]
Your HMR example is now in the angularjs seed
https://github.com/TobiasTimm/fuse-box-angularjs-example/blob/master/src/hmr.js
